;
; examples/production_cluster/extconfig.conf
; Realtime mappings to Tarantool 3.x in-memory database
;

[settings]
ps_endpoints => tarantool,tnt1,ps_endpoints
ps_auths     => tarantool,tnt1,ps_auths
ps_aors      => tarantool,tnt1,ps_aors
extensions   => tarantool,tnt1,extensions
